version: '3'

services:
  web:
    build: .
    command: gunicorn.blog.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_file:/app/media
      - static_file:/app/static
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .prod.db.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_file:/app/media
      - static_file:/app/static
    depends_on:
      - web


volumes:
  media_file:
  static_file:
  pgdata:


